pulsar:
  service-url: ${PULSAR_SERVICE_URL:pulsar+ssl://pulsar-gcp-useast4.streaming.datastax.com:6651}
  authentication: ${PULSAR_AUTHENTICATION:eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbGllbnQ7OTQyZWJiNTktNDQxNC00MGNjLWE0NTktYmJkMjgyN2NhNTVkO2RHNXVkQT09In0.twaKQ-Q6RSH-nIjrgC9Uqpsb02u_v0uYSqoxctASEvJm2MC__9B3u7GSn9X_URQQeBIPtQyKMyR_fOr8WLQXlWI9-QH-sfRSsvtQ3BqLOSh9czOJEWhUXekmcFXG8NK3E6RRB4pQtpSgOi9qMt2kL-Kox2fdbtLmsTuAB0DvjoIp_liF10ST9Pja_aRRO9WS_tCJYwv-rQI4IDB40gZPeC6_qW0uVogh_dqnZtIQ7HnR_2kSNfWkvncDaes6IdN-ehL2phm8bwz8VBxmbmAadN-nZmt9553nRXERcjFuKhSdEPqJCJ9-p4qKq81dvEtbedOaLvl22irvOd-7USsYWA}
  tenant: ${PULSAR_TENANT:tnnt}
  topic: ${PULSAR_TOPIC_IN_MESSAGES_IN_MESSAGES:persistent://tnnt/default/my-topic}
  topicRealTime: ${PULSAR_TOPIC_MESSAGES_OUT_NON_PERSISTENT:persistent://tnnt/default/real-time}
  topicPersistMessages: ${PULSAR_TOPIC_MESSAGE_PERSIST:persistent://tnnt/default/persist-messages}

server:
  port: 8092

spring:
  application:
    name: MESSAGE-SERVICE

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-0
  client:
    register-with-eureka: ${EUREKA_SERVER_ENABLED:false}
    fetch-registry: ${EUREKA_SERVER_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}

astra:
  cloud-region: ${CLOUD_REGION:eu-central-1}
  database-id: ${DATABASE_ID:93c15b57-e663-4838-9665-54ad030cacf1}
  keyspace: ${KEYSPACE:chat_ks}
  client-id: ${CLIENT_ID:ZWuuHiEWQBykPibuchLmBbJR}
  client-secret: ${CLIENT_SECRET:,mOd,EhH7-MUfzKZPUiwYZR5Sner_PjA,,iAqjSqK23jUzy.xg_M1yRepqxAZ,jw7y7f172R3FysD+2AOBZkawoRlgbmrL3ME2_WZNQQScLX+UjueboT1OmirnA9c36t}
  application-token: ${APPLICATION_TOKEN:AstraCS:ZWuuHiEWQBykPibuchLmBbJR:2fd8f9a1d48bc389d2abce20c40f4a75003584921e1a07b5616b27a2907fdbfe}

logging:
  level:
    root: INFO