apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway-app
  labels:
    app: cloud-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-gateway-app
  template:
    metadata:
      labels:
        app: cloud-gateway-app
    spec:
      containers:
        - name: cloud-gateway-app
          image: shynggys/io.bytestreme.cloud-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: EUREKA_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: EUREKA_SERVICE_URL
            - name: EUREKA_SERVER_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: EUREKA_SERVER_ENABLED
            - name: CONFIG_SERVER_URI
              valueFrom:
                configMapKeyRef:
                  name: cloud-config-cm
                  key: CONFIG_SERVER_URI
            - name: CONFIG_SERVER_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: cloud-config-cm
                  key: CONFIG_SERVER_ENABLED
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-cm
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-cm
                  key: REDIS_PORT
            - name: SECURITY_JWT_VERSION_CLAIM
              valueFrom:
                configMapKeyRef:
                  name: gateway-cm
                  key: SECURITY_JWT_VERSION_CLAIM
            - name: SECURITY_JWT_REDIS_TOKEN_VERSION_KEY
              valueFrom:
                configMapKeyRef:
                  name: gateway-cm
                  key: SECURITY_JWT_REDIS_TOKEN_VERSION_KEY
            - name: SECURITY_JWT_SIGN
              valueFrom:
                configMapKeyRef:
                  name: gateway-cm
                  key: SECURITY_JWT_SIGN
            - name: SECURITY_TOKEN_HEADER_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: gateway-cm
                  key: SECURITY_TOKEN_HEADER_PREFIX
            - name: SECURITY_TOKEN_WS_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: gateway-cm
                  key: SECURITY_TOKEN_WS_PREFIX
            - name: SECURITY_HEADER_FORWARDED
              valueFrom:
                configMapKeyRef:
                  name: gateway-cm
                  key: SECURITY_HEADER_FORWARDED

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: cloud-gateway-app

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-cm
data:
  SECURITY_JWT_SIGN: "chatjwt-key"
  SECURITY_JWT_VERSION_CLAIM: "token-version"
  SECURITY_JWT_REDIS_TOKEN_VERSION_KEY: "token-version"
  SECURITY_TOKEN_WS_PREFIX: "auth"
  SECURITY_TOKEN_HEADER_PREFIX: "Bearer "
  SECURITY_HEADER_FORWARDED: "X-Gateway-ID"