apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-service-app
  labels:
    app: metrics-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-service-app
  template:
    metadata:
      labels:
        app: metrics-service-app
    spec:
      containers:
        - name: metrics-service-app
          image: shynggys/io.bytestreme.metrics-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8283
          env:
            - name: CONFIG_SERVER_URI
              valueFrom:
                configMapKeyRef:
                  name: cloud-config-cm
                  key: CONFIG_SERVER_URI
            - name: EUREKA_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: EUREKA_SERVICE_URL
            - name: CONFIG_SERVER_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: cloud-config-cm
                  key: CONFIG_SERVER_ENABLED
            - name: EUREKA_SERVER_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: EUREKA_SERVER_ENABLED

---

kind: Service
apiVersion: v1
metadata:
  name: metrics-service-svc
spec:
  selector:
    app: metrics-service-app
  ports:
    - port: 80
      targetPort: 8283

