apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cm
data:
  REDIS_HOST: "redis-0.redis.default.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_CONFIG: ''
---

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  clusterIP: None
  ports:
    - port: 6379
      name: redis
  selector:
    app: redis

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: "redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:5.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
          command:
            - redis-server
            - "/redis-master/redis.conf"
          volumeMounts:
            - mountPath: /redis-master-data
              name: data
            - mountPath: /redis-master
              name: config
          env:
            - name: MASTER
              value: "true"
      volumes:
        - name: data
          emptyDir: { }
        - name: config
          configMap:
            name: redis-cm
            items:
              - key: REDIS_CONFIG
                path: redis.conf

---

apiVersion: v1
kind: Service
metadata:
  name: redis-lb
  labels:
    app: redis
spec:
  selector:
    app: redis
  type: NodePort
  ports:
    - port: 80
      targetPort: 6379
