apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-api-app
  labels:
    app: socket-api-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-api-app
  template:
    metadata:
      labels:
        app: socket-api-app
    spec:
      containers:
        - name: socket-api-app
          image: shynggys/io.bytestreme.socket-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: CONFIG_SERVER_URI
              valueFrom:
                configMapKeyRef:
                  name: cloud-config-cm
                  key: CONFIG_SERVER_URI
            - name: EUREKA_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: EUREKA_SERVICE_URL
            - name: CONFIG_SERVER_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: cloud-config-cm
                  key: CONFIG_SERVER_ENABLED
            - name: EUREKA_SERVER_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: EUREKA_SERVER_ENABLED
            - name: PULSAR_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: pulsar-cm
                  key: PULSAR_SERVICE_URL
            - name: PULSAR_AUTHENTICATION
              valueFrom:
                configMapKeyRef:
                  name: pulsar-cm
                  key: PULSAR_AUTHENTICATION
            - name: PULSAR_TENANT
              valueFrom:
                configMapKeyRef:
                  name: pulsar-cm
                  key: PULSAR_TENANT
            - name: PULSAR_TOPIC_IN_MESSAGES_IN_MESSAGES
              valueFrom:
                configMapKeyRef:
                  name: pulsar-cm
                  key: PULSAR_TOPIC_IN_MESSAGES_IN_MESSAGES
            - name: PULSAR_TOPIC_MESSAGES_OUT_NON_PERSISTENT
              valueFrom:
                configMapKeyRef:
                  name: pulsar-cm
                  key: PULSAR_TOPIC_MESSAGES_OUT_NON_PERSISTENT
---

kind: Service
apiVersion: v1
metadata:
  name: socket-api-svc
spec:
  selector:
    app: socket-api-app
  ports:
    - port: 80
      targetPort: 8082
