server:
  port: 8283

spring:
  application:
    name: METRICS_SERVICE

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-0
  client:
    register-with-eureka: ${EUREKA_SERVER_ENABLED:false}
    fetch-registry: ${EUREKA_SERVER_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
