server:
  port: 8888

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: ${GIT_CONFIG_URI}
          clone-on-start: true
          default-label: main

eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}